
name: grootly_app
description: Grootly is a user-friendly Flutter app that aims to empower individuals to live a more sustainable life, with a particular emphasis on food sustainability.

publish_to: 'none' 


version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/json/Frame-1.json
    - assets/images/example/
 
  fonts:
    - family: GrootlyIcons
      fonts:
        - asset: assets/icons/GrootlyIcons.ttf