
name: grootly_app
description: Grootly is a user-friendly Flutter app that aims to empower individuals to live a more sustainable life, with a particular emphasis on food sustainability.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  image_picker: ^1.0.4
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  flutter_native_splash: ^2.3.3
  font_awesome_flutter: ^10.6.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  email_validator: ^2.1.17
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher/grootly_launcher.png"
  adaptive_icon_background: "#39523F"
  adaptive_icon_foreground: "assets/icon_launcher/launcher_android.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#f5f5f5"
  image: assets/images/logo/grootly_logo2.png

flutter:

  uses-material-design: true

  assets:
    - assets/json/Frame-1.json
    - assets/json/grootly_logo2.json
    - assets/images/example/
    - assets/images/logo/

  fonts:
    - family: GrootlyIcons
      fonts:
        - asset: assets/icons/GrootlyIcons.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf